// mpvue/my-project/src/pages/index/index.vue
<template>
  <div class="content">
<van-card
  v-for="(item,index) of products"
  :key="index"
  tag="标签"
  :price="item.productPrice"
  :desc="item.productInfo"
  :title="item.productName"
  :thumb="item.productCover"
>
  <view slot="footer">
    <van-stepper  :value="item.productCount" @change="handleSte" :data-id="item.id"/>
      <van-checkbox  :value="item.isSelected" @change="handleChe(item.id)" >选中</van-checkbox>
    <van-button size="mini" @click="handleDle(index)">删除</van-button>
  </view>
</van-card>

<van-submit-bar
  :price="sum"
  button-text="提交订单"
  bind:submit="onClickButton"
>
  <van-checkbox :value="checkAll" @change="handleClick">全选</van-checkbox>
</van-submit-bar>
  </div>
</template>
<script>
export default {
  data() {
    return {
      products:[],
      checkAll:true
    }
  },
  onLoad () {
     var url = "http://yapi.demo.qunar.com/mock/34622/";
    this.$http.get(url).then(res=>{
      this.products = res.data
    })
},
  computed: {
    sum() {
      var total = 0;
      for (let i = 0; i < this.products.length; i++) {
        if (this.products[i].isSelected) {
          total =
            total +
            this.products[i].productCount * this.products[i].productPrice;
        } else {
          continue;
        }
      }
      return total * 100;
    }
  },
  methods: {
    handleChe(id){
      this.products.forEach(item=>{
        if(item.id==id){
         item.isSelected = !item.isSelected
        }
      })
      this.checkAll = this.products.every(item=>item.isSelected)

    },
    handleClick(){
      this.checkAll = !this.checkAll
      this.products.forEach(item=>{
        item.isSelected = this.checkAll
      })
    },
    handleSte(e){
      var id = e.target.dataset.id
       this.products.forEach(item=>{
        if(item.id==id){
         item.productCount = e.mp.detail
        }
      })
    },
    handleDle(index){
       this.products.splice(index, 1);
    }
  },

}
</script>
<style scoped>
.content{
  height: 1500px;
}
</style>

// taro/taro-cart/src/pages/index/index.jsx
import Taro, { Component } from '@tarojs/taro'
import { View, Text, Image, Button, Checkbox} from '@tarojs/components'
import './index.css'
import {  AtInputNumber} from 'taro-ui'

export default class Index extends Component {
  constructor() {
    super(...arguments)
    this.state = {
      book: [],
      allchecked: true
    }
  }
  handleNumber(id,e){
    var book = this.state.book
    book.forEach(item=>{
      if(id==item.id){
        item.productCount =e
      }
      this.setState({
        book
      })
    })
  }

  handleChange(id, e) {
    var book = this.state.book
    book.forEach(item => {
      if (id == item.id) {
        item.isSelected = !item.isSelected
      }
    })
    this.setState({
      book
    })
    var allchecked = book.every(item => item.isSelected)
    this.setState({
      allchecked
    })
  }
  handleClick(e) {
    var allchecked = this.state.allchecked
    this.setState({
      allchecked: !allchecked
    })
    var book = this.state.book
    book.map(item => (item.isSelected = !allchecked));
    this.setState({
      book
    })
  }
  handleDle(index) {
    var book = this.state.book
    book.splice(index, 1)
    this.setState({
      book
    })
  }

  sum() {
    var total = 0;
    var book = this.state.book
    for (let i = 0; i < book.length; i++) {
      if (book[i].isSelected) {
        total =
          total +
          book[i].productCount * book[i].productPrice;
      } else {
        continue;
      }
    }
    return total.toFixed(2)
  }

  componentWillMount() {
    Taro.request({
      url: 'http://yapi.demo.qunar.com/mock/34622/',
      data: {
        foo: 'foo',
        bar: 10
      },
      header: {
        'content-type': 'application/json'
      }
    })
      .then(res =>
        this.setState({
          book: res.data
        })
      )
  }

  render() {
    return (
      <View className='index'>
        <View>{this.state.book.map((item, index) => {
          return (
            <View className="nav" key={item.id}>
              <Checkbox checked={item.isSelected} onClick={this.handleChange.bind(this, item.id)} />
              <Image src={item.productCover} />
              <view className="nav-content">
                <view>{item.productName}</view>
                <view>{item.productInfo}</view>
                <Viwe>$:{item.productPrice}</Viwe>
                <View><AtInputNumber
                  min={0}
                  max={10}
                  step={1}
                  value={item.productCount}
                  onChange={this.handleNumber.bind(this,item.id)}
                /></View>
                <view>小计：{item.productPrice * item.productCount}</view>
                <Text onClick={this.handleDle.bind(this, index)}>删除</Text>
              </view>

            </View>
          )
        })}</View>
        <Checkbox checked={this.state.allchecked} onClick={this.handleClick.bind(this)}>全选</Checkbox>
        <View>总价：{this.sum()}</View>
      </View>
    )
  }
}
